title: Oles Tourko
baseurl: ''
exclude: ['README.md']
theme: jekyll-theme-architect
show_downloads: false
permalink: /:year/:month/:day/:title.html

github:
  is_project_page: false
  is_user_page: true

collections:
  notes:
    output: true